#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
setopt PROMPT_SP

PATH="/home/zetatwo/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/home/zetatwo/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/zetatwo/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/zetatwo/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/zetatwo/perl5"; export PERL_MM_OPT;

alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
alias pwnlayout="tmux split-window -d -h 'tty;cat'"

if command -v exa &> /dev/null; then
  alias ls='exa'
fi
if command -v duf &> /dev/null; then
  alias df='duf'
fi
if command -v dust &> /dev/null; then
  alias du='dust'
fi
if command -v rg &> /dev/null; then
  alias grep='rg'
fi
if command -v procs &> /dev/null; then
  alias ps='procs'
fi

stream-status () {
  curl -s 'http://127.0.0.1:9090/zetatwo/status' --data "status=$1" > /dev/null
  LOGFILE="$HOME/stream-status.log"
  touch $LOGFILE && echo "$(date +%s) $1" >> $LOGFILE
}

ssm-status () {
  stream-status "Säkerhets-SM - $1"
}

genz-status () {
  stream-status "Gen Z Hack Challenge 2021 - $1"
}

# pyenv
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv virtualenv-init -)"


autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/bin/terraform terraform

### LS25 Deploy commands ###
alias ls25_deploy="poetry run ansible-playbook start.yml -e=@~/Projects/ls25/ls25/credentials --ask-vault-pass -e=deploy_mode=deploy -l "
alias ls25_deployr="poetry run ansible-playbook start.yml -e=@~/Projects/ls25/ls25/credentials --ask-vault-pass -e=deploy_mode=deploy -e role_only=true -l "
alias ls25_undeploy="poetry run ansible-playbook start.yml -e=@~/Projects/ls25/ls25/credentials --ask-vault-pass -e=deploy_mode=undeploy -l "
alias ls25_redeploy="poetry run ansible-playbook start.yml -e=@~/Projects/ls25/ls25/credentials --ask-vault-pass -e=deploy_mode=redeploy -l "
alias ls25_deploy-poweron="poetry run ansible-playbook start.yml -e=@~/Projects/ls25/ls25/credentials --ask-vault-pass -e=deploy_mode=deploy -e=poweron=yes -e=pre_role=ccdcoe.core.powerstate -l "
alias ls25_deploy-poweroff="poetry run ansible-playbook start.yml -e=@~/Projects/ls25/ls25/credentials --ask-vault-pass -e=deploy_mode=deploy -e=shutdown=yes -e=pre_role=ccdcoe.core.powerstate -l "
alias ls25_deploy-resnap="poetry run ansible-playbook start.yml -e=@~/Projects/ls25/ls25/credentials --ask-vault-pass -e=deploy_mode=deploy -e=snap_mode=resnap -l "
alias ls25_deploy-snap="poetry run ansible-playbook start.yml -e=@~/Projects/ls25/ls25/credentials --ask-vault-pass -e=deploy_mode=deploy -e=snapshot_mode=snap -e pre_role=nova.core.snapshots -l "
alias ls25_get-ansible-vars="poetry run ansible-inventory -e=@~/Projects/ls25/ls25/credentials --ask-vault-pass --vars --host "
alias ls25_get-ansible-hosts="poetry run ansible-playbook start.yml -e=@~/Projects/ls25/ls25/credentials --ask-vault-pass -e=deploy_mode=deploy --list-hosts -l "


eval "$(atuin init zsh)"

export WASMTIME_HOME="$HOME/.wasmtime"
export PATH="$WASMTIME_HOME/bin:$PATH"

# bun completions
[ -s "/home/zetatwo/.bun/_bun" ] && source "/home/zetatwo/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

. "$HOME/.atuin/bin/env"
