#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
setopt PROMPT_SP

PATH="/home/zetatwo/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/home/zetatwo/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/zetatwo/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/zetatwo/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/zetatwo/perl5"; export PERL_MM_OPT;

#export PATH=/home/zetatwo/tools/fomu-toolchain/bin:$PATH
export SDCCDIR=/home/zetatwo/tools/sdcc
. "/home/zetatwo/.acme.sh/acme.sh.env"
export PATH=$PATH:/home/zetatwo/tools/010editor;
export PATH="$HOME/.cargo/bin:$PATH"

alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
alias pwnlayout="tmux split-window -d -h 'tty;cat'"
